# Generated by Django 3.1.2 on 2021-02-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(default='', upload_to='Home/images'),
        ),
    ]
