# Generated by Django 3.1.2 on 2021-02-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='test',
            field=models.TextField(default=''),
        ),
    ]
