# Generated by Django 3.1.2 on 2021-02-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_data_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
