# Generated by Django 3.1.2 on 2021-02-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20210209_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_1', models.CharField(max_length=200)),
                ('description_2', models.CharField(max_length=200)),
                ('description_3', models.CharField(max_length=200)),
                ('description_4', models.CharField(max_length=200)),
                ('description_5', models.CharField(max_length=200)),
                ('description_6', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('telegram_id', models.CharField(max_length=200)),
                ('Resume', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
